<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php include 'head.inc'; ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php ob_start(); ?>
    <?php echo $this->getChildHtml('after_body_start') ?>
    <div data-role="page">
        <div data-role="header"  data-theme="c">
            <h1 id="productname"><?php echo $this->getLayout()->getBlock('head')->getTitle(); ?></h1>
        </div>
        <div class="wrapper" data-role="content">
            <?php echo $this->getChildHtml('global_notices') ?>
            <div class="page">
                <?php echo $this->getChildHtml('header') ?>
                <div class="main-container">
                    <div class="main">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('content') ?>
                        <br/>
                        <?php echo $this->getChildHtml('breadcrumbs') ?>
                        <?php /*
                          <div class="col-right sidebar"><?php echo $this->getChildHtml('right') ?></div>
                         */ ?>
                    </div>
                </div>
                <?php //echo $this->getChildHtml('footer') ?>
                <?php //echo $this->getChildHtml('before_body_end') ?>
                    </div>
                </div>
        <?php echo $this->getAbsoluteFooter() ?>
    </div>
    <?php $body = ob_get_flush();
    echo preg_replace("@<script[^>]*>.+</script[^>]*>@i", "", $body);
    ?>
</body>
</html>
